### ISSUE TITLE
feature: Disallow capital labels

### ISSUE THREAD

**Issue by jradam** [folke/flash.nvim#11]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

Love this! Though I find it a little cumbersome to have to type capital letters. Would it be possible to disallow capitals from the label list?

For example, if you have the labels set up as:
`labels = "abcdefghijklmnopqrstuvwxyz"`

You will get labels such as `A` or `B` show up when there are lots of matches, and I would like to only allow `a` or `b`.

In the event that there are more than 26 matches, I would prefer to have to be more specific with my search, rather than use capitals.

### Describe the solution you'd like

Could an option like this be added?
```
restrict_case: 'lowercase' -- options: 'lowercase' | 'uppercase' | false
```

### Describe alternatives you've considered

You could also make the option a simple boolean, since I doubt anyone would want uppercase only:
```
lowercase_only: true
```

Or alternatively, you could do something like this to allow all alphas:
`labels = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"`

Or this to only allow lowercase:
`labels = "abcdefghijklmnopqrstuvwxyz"`

Or indeed this to only allow uppercase:
`labels = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"`

**Comment by folke** [comment]
First lowercase then uppercase labels are used. Labels are distributed to targets based on the window/cursor distance from the current cursor position.

Flash also tries to re-use labels that were already assigned when typing more characters in order to "stabilize" a target's label.

So this means that after typing one character, a far away target might've gotten am upper-case label.

Now when typing more characters, that far-away target would keep its original label, which is preferable I think, instead of changing labels.

Turns out there is a better way.

I just pushed a change so that by default, only lower-case labels will be re-used.

I'll see to make your feature request also configurable, but the fix I pushed is probably already solving this

**Comment by jradam** [comment]
Nice! That was quick. I think that solves this. Would be cool to have it configurable too I suppose, but I don't think it's that important. Thanks!

**Comment by userrand** [comment]
I would also prefer to avoid capitals. At the moment it seems the algorithm chooses a capital letter like `B` if  `b` is also a label. But capital letters are hard to type. I would rather it tried any of the 26 letter or other characters like , or ; before it chooses a capital letter. 

That is, at least for me, it would be nice, if it only chose capital letters last. 

This might already be implemented when typing 2 characters as I noticed that a capital letter label might turn to a different lower-case letter if 2 instead of 1 letter is typed

**Comment by userrand** [comment]
At least for me, It would also be nice if the order in which the characters were placed in the labels option was preserved as a priority order. That is, for an option setting such as `labels="abcd"` , a is always used as a label before b, b is always used as a label before c, etc.
