### ISSUE TITLE
feature: string converting function

### ISSUE THREAD

**Issue by ryoppippi** [folke/flash.nvim#14]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to configure "string conversion function" for input .
For example, I want to insert a plugin that enumerates Japanese candidates from alphabet between input and search results

(ex. migemo https://github.com/lambdalisue/kensaku.vim)

### Describe the solution you'd like

create an option to configure function

### Describe alternatives you've considered

hmm

**Comment by folke** [comment]
I dont really understand what that plugin does that you linked to.

Can you be more specific on what would be needed or on what you want to achieve?

Is it the input that you type that should be converted to another pattern used for search?

**Comment by ryoppippi** [comment]
For example
```
input | result
-------------
kaisan | 解散
ohanashi|お話し
```

When you write Japanese or Korean, people type alphabet, but the alphabets are converted to another characters like Kanji

so, I just want to set a text conversion function that accepts users input and return some other strings

**Comment by ryoppippi** [comment]
It is also known as migemo (https://www.npmjs.com/package/migemo)
I'd like to combine these functions to find characters and jump them.

**Comment by folke** [comment]
So you want to type `kaisan` and the search should use those japanese symbols?

You want a function that takes `kaisan` as input and you will implement that function so that it returns those symbols to use in a search?

**Comment by ryoppippi** [comment]
I'd like to customize the input-output conversion function.
You don't need to implement these functions.

**Comment by ryoppippi** [comment]
> So you want to type kaisan and the search should use those japanese symbols?

yes

> You want a function that takes kaisan as input and you will implement that function so that it returns those symbols to use in a search?

Yes, that's right.
But we do not need to implement the function itself, I just want to put that function between the input and the output.

**Comment by folke** [comment]
I still don't get it fully.

Can you respond to my previous question directly?

I'm willing to look into this, but then of course I first need to fully understand the requirements.

An input-output conversion function is too vague.

**Comment by folke** [comment]
ok, so you should be able to configure a function that will be used to
convert the input you type to something that will be used as a search string

**Comment by folke** [comment]
I'll look into it tomorrow!

**Comment by ryoppippi** [comment]
> convert the input you type to something that will be used as a search string
Yes, that's the point!! Huge thanks.


Btw, this is another easymotion-like plugin. This plugin is doing as I said.
https://github.com/yuki-yano/fuzzy-motion.vim/blob/main/denops/fuzzy-motion/kensaku.ts

**Comment by ryoppippi** [comment]
Sorry, but I have a feeling that what I want to do is possible by assigning a function to `search.mode`

**Comment by folke** [comment]
ah yes, you can use that for your purpose

**Comment by Fuann-Kinoko** [comment]
Hi, I think this issue currently cannot be solved by tweaking existing modes

So in Japanese or Korean, the shapes of characters (like kanji) are separated from their pronunciations, or like to say, same combination of alphabets can result in different characters, leading to different meanings.

For example, typing `kaisan` can output following kanjis:
```
kaisan -> 解散 : dissolution
kaisan -> 海産 : marine products
kaisan -> かいさん : the hiragana version of kaisan
kaisan -> カイサン : the katakana version of kaisan
```
it's hard for `flash.nvim` to filter the characters you want to input because their shapes can't be determined by pronounciations, and it's inconvinent for users to:
1. trigger `flash.nvim`
2. type `kaisan` (it can't match any kanji)
3. select the kanji you want from IME
4. `flash.nvim` hints the jump points

instead, we want to:
1. trigger `flash.nvim`
2. type `kaisan`
3. `flash.nvim` hints any matched kanjis on the screen, including 解散, 海産 or other things

and that requires a dictionary to help `flash.nvim` to look up, which is avaliable in the formentioned [migemo](https://github.com/emacs-jp/migemo)

similar features for vim have been added in [easymotion](https://github.com/easymotion/vim-easymotion#migemo-feature-for-japanese-user), and it's using the dictionary from cmigemo.
