### ISSUE TITLE
feature: unconceal when jump activated

### ISSUE THREAD

**Issue by haoming-li-ling** [folke/flash.nvim#182]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When I try to `require("flash").jump()` with conceal enabled on a buffer, the concealed characters don't revert to the original, unlike the behavior when using the `/` and `?`search function of flash, or the jump function in `leap`.

### Describe the solution you'd like

Unconceal characters when using `require("flash").jump()`.

### Describe alternatives you've considered

I can't think of any.

**Comment by folke** [comment]
The unconceal happening with regular search is actually a fix for  Neovim bug in Noice. Without Noice, you wouldn't have that behavior.

But I'll see to make this an option for flash as well.

**Comment by roginfarrer** [comment]
Just wanted to bump this issue since I'm running into the same challenge. I use a plugin for markdown that conceals characters to make a nicer reading experience (markdown.nvim). I was looking for ways to drop concealment when in operator-pending modes. It doesn't look like Flash uses that mode, nor is there a hook to change settings when flash is started.

One alternative is to wrap this functionality around the keymaps, which I'll look into. But it would be nice to have a universal hook for this! Either an autocmd for `FlashEnter` and `FlashLeave` or config hooks like `on_enter` and `on_leave`.
