### ISSUE TITLE
feature: can treesitter_search go back in original window/cursor just like remote did?

### ISSUE THREAD

**Issue by Marskey** [folke/flash.nvim#380]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

none

### Describe the solution you'd like

after I finish treesitter_search I can go back to original cursor/window. I saw there is config 
``` lua   
remote_op = { restore = true }, 
```
 but its not working. correct me if Im wrong

### Describe alternatives you've considered

Maybe I can add ```lua  vim.cmd ":normal! <c-o>"``` to somewhere

**Comment by ajvondrak** [comment]
Hey @Marskey and anyone else passing by this issue, I noticed the same thing and think I figured out a workaround. It turns out that despite passing `remote_op` options into `treesitter_search` by default here: https://github.com/folke/flash.nvim/blob/3c942666f115e2811e959eabbdd361a025db8b63/lua/flash/config.lua#L230 the implementation doesn't actually ever _call_ the `remote_op` function responsible for handling the cursor restore: https://github.com/folke/flash.nvim/blob/3c942666f115e2811e959eabbdd361a025db8b63/lua/flash/jump.lua#L59 I.e., the `search` function doesn't go through `jump` which knows to process the `remote_op` options, it calls `state:loop` manually: https://github.com/folke/flash.nvim/blob/3c942666f115e2811e959eabbdd361a025db8b63/lua/flash/plugins/treesitter.lua#L182-L186

The workaround I have is to manually invoke the `remote_op` function from the `action`:

```lua
    {
      "R",
      mode = "o",
      function()
        local register = vim.v.register
        require("flash").treesitter_search({
          action = function(match, state)
            require("flash.jump").remote_op(match, state, register)
          end,
        })
      end,
      desc = "Remote Treesitter Flash",
    }
```

Hope that helps!
